from .constants import SERVICOS, MUNICIPIOS, TIPOS_DE_INSPECAO

COMMON = {"status": "", "description": "", "start_date": "", "due_date": ""}

TECNICA = COMMON | {
    "agrupamento": {"id": 213, "name": "Agrupamento", "value": ""},
    "altura_do_sistema_irradiante": {
        "id": 131,
        "name": "Altura do sistema irradiante",
        "value": "",
    },
    "ano_de_execucao": {"id": 5, "name": "Ano de Execução", "value": ""},
    "app_fiscaliza": {"id": 463, "name": "App Fiscaliza", "value": ""},
    "area_do_pacp": {
        "id": 416,
        "name": "Área do PACP",
        "map": [
            "1-Comércio",
            "2-ISP",
            "3-E-commerce",
            "4-Aduana",
            "5-Feiras e Eventos",
            "6-Supervisão de Mercados",
        ],
        "value": {"texto": "", "valor": ""},
    },
    "classe_da_inspecao": {
        "id": 89,
        "name": "Classe da Inspeção",
        "value": {"valor": "", "texto": ""},
    },
    "coordenacao_responsavel": {
        "id": 178,
        "name": "Coordenação responsável",
        "value": "",
    },
    "coordenadas_geograficas": {
        "id": 717,
        "name": "Coordenadas Geográficas",
        "value": "",
    },
    "data_de_inicio_efetivo": {
        "id": 627,
        "name": "Data de início efetivo",
        "value": "",
    },
    "documento_instaurador_do_pado": {
        "id": 134,
        "name": "Documento instaurador do PADO",
        "value": "",
    },
    "dadospacp": {"id": 415, "name": "DadosPACP", "value": ""},
    "entidade_com_cadastro_stel": {
        "id": 189,
        "name": "Entidade com " "cadastro STEL?",
        "map": ["Sim", "Não"],
        "value": "",
    },
    "entidade_da_inspecao": {
        "id": 30,
        "name": "Entidade da Inspeção",
        "multiple": True,
        "value": [""],
    },
    "entidade_outorgada": {"id": 138, "name": "Entidade outorgada?", "value": ""},
    "esta_em_operacao": {"id": 139, "name": "Está em operação?", "value": ""},
    "fiscal_responsavel": {"id": 25, "name": "Fiscal responsável", "value": ""},
    "fiscais": {"id": 26, "name": "Fiscais", "multiple": True, "value": [""]},
    "frequencias": {"id": 180, "name": "Frequência(s)", "value": ""},
    "horas_de_conclusao": {"id": 94, "name": "Horas de conclusão", "value": ""},
    "horas_de_deslocamento": {
        "id": 92,
        "name": "Horas de Deslocamento",
        "value": "",
    },
    "horas_de_execucao": {"id": 93, "name": "Horas de Execução", "value": ""},
    "horas_de_preparacao": {"id": 91, "name": "Horas de Preparação", "value": ""},
    "houve_interferencia": {"id": 149, "name": "Houve interferência?", "value": ""},
    "houve_obice": {
        "id": 136,
        "name": "Houve óbice?",
        "map": ["Sim", "Não"],
        "value": "",
    },
    "irregularidade": {
        "id": 73,
        "name": "Irregularidade",
        "multiple": True,
        "map": ["Comercialização de produtos", "Utilização de produtos"],
        "value": [{"valor": "", "texto": ""}],
    },
    "latitude_coordenadas": {
        "id": 170,
        "name": "Latitude (coordenadas)",
        "value": "",
    },
    "longitude_coordenadas": {
        "id": 171,
        "name": "Longitude (coordenadas)",
        "value": "",
    },
    "no_pcdp": {"id": 112, "name": "Nº PCDP", "value": ""},
    "no_sav": {"id": 111, "name": "Nº SAV", "value": ""},
    "no_sei_processo_fiscalizacao": {
        "id": 422,
        "name": "Nº SEI Processo Fiscalização",
        "replace_colon": True,
        "value": {"numero": ""},
    },
    "observacao_tecnica_amostral": {
        "id": 693,
        "name": "Observação (técnica amostral)",
        "value": "",
    },
    "potencia_medida": {"id": 81, "name": "Potência medida", "value": ""},
    "precisa_reservar_instrumentos": {
        "id": 596,
        "name": "Precisa reservar instrumentos?",
        "value": "",
    },
    "procedimentos": {
        "id": 71,
        "name": "Procedimentos",
        "multiple": True,
        "map": [
            "Nenhum",
            "Lacração",
            "Apreensão",
            "Interrupção",
            "Não Cadastrado",
            "Notificado",
            "A Notificar",
            "Liberação/Desinterrupção",
            "Orientação ao Usuário",
            "Comunicado",
            "Deslacrado",
            "Vistoriado",
            "Emissão Termo Violação de Lacre",
            "Apoio a busca e apreensão",
            "Investigação/Pesquisa",
            "Não Lacrado - Impedimento",
            "Não Lacrado - Amparo Judicial",
            "Não Lacrado - Responsável Ausente",
            "Não Lacrado - Local Fechado",
            "Constatação Violação Lacre/Relacrado",
            "Constatação Violação Lacre/Impedimento",
            "Notícia Crime",
            "Monitorado alterado",
            "Constatação Encerramento - Informe",
            "Levantamento de Dados",
            "Análise/coleta de Dados",
            "Monitorado",
            "Não Lacrado - Desativado",
            "Devolução de Produto(s)",
        ],
        "value": [],
    },
    "qnt_produt_lacradosapreend": {
        "id": 143,
        "name": "Qnt. produt. " "lacrados/apreend.",
        "value": "",
    },
    "servicos_da_inspecao": {
        "id": 57,
        "name": "Serviços da Inspeção",
        "multiple": True,
        "map": SERVICOS,
        "value": [{"valor": "", "texto": ""}],
    },
    "situacao_constatada": {
        "id": 62,
        "name": "Situação constatada",
        "map": ["Regular", "Irregular", "Inconclusivo", "Não analisado"],
        "value": "",
    },
    "situacao_de_risco_a_vida": {
        "id": 150,
        "name": "Situação de risco à vida?",
        "value": {"valor": "", "texto": ""},
    },
    "subtema": {
        "id": 15,
        "name": "Subtema",
        "multiple": True,
        "value": [{"valor": "", "texto": ""}],
    },
    "tema": {
        "id": 14,
        "name": "Tema",
        "multiple": True,
        "value": [{"valor": "", "texto": ""}],
    },
    "tipo_de_inspecao": {
        "id": 2,
        "name": "Tipo de inspeção",
        "map": TIPOS_DE_INSPECAO["Técnica"],
        "value": {"valor": "", "texto": ""},
    },
    "total_de_horas": {"id": 1789, "name": "Total de horas", "value": ""},
    "ufmunicipio": {
        "id": 31,
        "name": "UF/Município",
        "multiple": True,
        "map": MUNICIPIOS,
        "value": [{"valor": "", "texto": ""}],
    },
    "unidade_de_frequencia": {
        "id": 84,
        "name": "Unidade de Frequência",
        "value": "",
    },
    "unidade_de_potencia": {"id": 82, "name": "Unidade de Potência", "value": ""},
    "uso_de_produto_homologado": {
        "id": 132,
        "name": "Uso de produto homologado?",
        "value": "",
    },
    "utilizou_algum_instrumento": {
        "id": 598,
        "name": "Utilizou algum instrumento?",
        "map": ["1", "0"],
        "value": "",
    },
    "utilizou_apoio_policial": {
        "id": 75,
        "name": "Utilizou apoio policial?",
        "value": "",
    },
    "utilizou_tecnicas_amostrais": {
        "id": 692,
        "name": "Utilizou técnicas amostrais?",
        "map": ["Usou técnicas amostrais", "Não usou técnicas amostrais"],
        "value": "",
    },
}
