from datatypes import (
    SimpleField,
    EncodedString,
    FieldWithOptions,
    Coordenadas,
    GerarPlai,
)
from constants import MUNICIPIOS, SERVICOS

ALL = {"status": "", "description": "", "start_date": "", "due_date": ""}

SPECIAL = [
    "latitude_coordenadas",
    "longitude_coordenadas",
    "latitude_da_estacao",
    "longitude_da_estacao",
    "gerar_plai",
]

HIDDEN = {
    "gerar_plai": {
        "id": 426,
        "name": "Gerar PLAI",
        "tipo_processo": {
            "Gestão da Fiscalização: Lacração, Apreensão e Interrupção": "100000539",
            "Gestão da Fiscalização: Processo de Guarda": "100000618",
        },
        "replace_colon": True,
        "value": {"criar_processo": "", "tipo_processo": "", "coord_fi": ""},
    },
    "gerar_relatorio": {
        "id": 541,
        "name": "Gerar Relatório",
        "map": {"1": {"mandatory": ["Html"]}, "0": {}},
        "value": "",
    },
    "Html": {
        "id": 543,
        "name": "Html",
        "value": "",
    },
}

TIPOS_DE_INSPECAO = {
    "Técnica": [
        "agrupamento",
        "coordenacao_responsavel",
        "entidade_da_inspecao",
        "fiscais",
        "fiscal_responsavel",
        "horas_de_conclusao",
        "horas_de_deslocamento",
        "horas_de_execucao",
        "horas_de_preparacao",
        "no_pcdp",
        "no_sav",
        "no_sei_processo_fiscalizacao",
        "precisa_reservar_instrumentos",
        "procedimentos",
        "servicos_da_inspecao",
        "tipo_de_inspecao",
        "ufmunicipio",
        "utilizou_algum_instrumento",
    ]
}


FIELDS = {
    "acao_de_risco_a_vida_criada": SimpleField(154, "Ação de risco à vida criada?"),
    "agrupamento": SimpleField(213, "Agrupamento"),
    "altura_do_sistema_irradiante": SimpleField(131, "Altura do sistema irradiante"),
    "area_do_pacp": FieldWithOptions(
        416,
        "Área do PACP",
        options=[
            "1-Comércio",
            "2-ISP",
            "3-E-commerce",
            "4-Aduana",
            "5-Feiras e Eventos",
            "6-Supervisão de Mercados",
        ],
        format_value=True,
    ),
    "campo_eletrico__pico_vm": SimpleField(195, "Campo elétrico - pico (V/m)"),
    "campo_eletrico_rms_vm": SimpleField(194, "Campo elétrico RMS (V/m)"),
    "cnpjcpf_da_entidade": SimpleField(141, "CNPJ/CPF da Entidade"),
    "coordenacao_responsavel": SimpleField(178, "Coordenação responsável"),
    "coordenadas_estacao": SimpleField(718, "Coordenadas Estação"),
    "coordenadas_geograficas": Coordenadas(717, "Coordenadas Geográficas"),
    "copiar_instrumento_da_reserva": FieldWithOptions(
        629, "Copiar instrumento da reserva?", options=["0", "1"]
    ),
    "dadospacp": SimpleField(415, "DadosPACP"),
    "documento_instaurador_do_pado": SimpleField(134, "Documento instaurador do PADO"),
    "endereco_da_inspecao": SimpleField(142, "Endereço da Inspeção"),
    "entidade_com_cadastro_stel": FieldWithOptions(
        189, "Entidade com cadastro STEL?", True, options=["Sim", "Não"]
    ),
    "entidade_da_inspecao": SimpleField(30, "Entidade da Inspeção", True),
    "entidade_outorgada": FieldWithOptions(
        138,
        "Entidade outorgada?",
        options=["0", "1"],
        mapping={"1": ["numero_da_estacao"]},
    ),
    "esta_em_operacao": FieldWithOptions(139, "Está em operação?", options=["0", "1"]),
    "fiscais": SimpleField(26, "Fiscais", True, True),
    "fiscal_responsavel": SimpleField(25, "Fiscal responsável", True),
    "foi_constatada_interferencia": FieldWithOptions(
        1967, "Foi constatada interferência?", options=["0", "1"]
    ),
    "frequencia_inicial": SimpleField(156, "Frequência inicial", True),
    "frequencia_final": SimpleField(158, "Frequência final", True),
    "frequencias": SimpleField(180, "Frequência(s)"),
    "horas_de_conclusao": SimpleField(94, "Horas de conclusão", True),
    "horas_de_deslocamento": SimpleField(92, "Horas de deslocamento", True),
    "horas_de_execucao": SimpleField(93, "Horas de Execução", True),
    "horas_de_preparacao": SimpleField(91, "Horas de Preparação", True),
    "houve_interferencia": FieldWithOptions(
        149,
        "Houve interferência?",
        True,
        options=["Sim", "Não"],
        mapping={"Sim": ["identificada_a_origem"]},
    ),
    "houve_obice": FieldWithOptions(136, "Houve óbice?", True, options=["0", "1"]),
    "identificada_a_origem": FieldWithOptions(
        162,
        "Identificada a origem?",
        True,
        options=["0", "1"],
        mapping={"1": ["sanada_ou_mitigada"]},
    ),
    "identificacao_da_nao_outorgada": SimpleField(
        250, "Identificação da não Outorgada"
    ),
    "instrumentos_utilizados": SimpleField(599, "Instrumentos Utilizados", True),
    "irregularidade": FieldWithOptions(
        73,
        "Irregularidade",
        multiple=True,
        options=[
            "Comercialização de produtos",
            "Utilização de produtos",
            "Conteúdo",
            "Outros aspectos não técnicos",
            "Recursos de acessibilidade",
            "Frequência diversa da autorizada",
            "Local da estação diverso do autorizado",
            "Outras irregularidades técnicas (especificar)",
            "Potência diversa da autorizada",
        ],
        format_value=True,
    ),
    "lai_vinculadas": SimpleField(481, "LAI vinculadas"),
    "latitude_coordenadas": SimpleField(170, "Latitude (coordenadas)"),
    "latitude_da_estacao": SimpleField(191, "Latitude da estação"),
    "longitude_coordenadas": SimpleField(171, "Longitude (coordenadas)"),
    "longitude_da_estacao": SimpleField(192, "Longitude da estação"),
    "motivo_de_lai": FieldWithOptions(
        164,
        "Motivo de LAI",
        multiple=True,
        options=[
            "Risco à vida",
            "Clandestinidade",
            "Interferência prejudicial",
            "Uso de produto não certificado",
            " Garantir a segurança (exposição a campos eletromagnéticos)",
            " Necessidade de assegurar o planejamento, o gerenciamento e a coordenação do uso de espectro de radiofrequências (justificar)",
        ],
    ),
    "numero_da_estacao": SimpleField(137, "Número da estação", True),
    "no_de_homologacao": SimpleField(161, "Nº de homologação"),
    "no_do_lacre": SimpleField(165, "Nº do lacre"),
    "no_pcdp": SimpleField(112, "Nº PCDP"),
    "no_sav": SimpleField(111, "Nº SAV"),
    "no_sei_do_aviso_lai": EncodedString(427, "Nº SEI do Aviso LAI"),
    "no_sei_do_plaiguarda": EncodedString(426, "Nº SEI do PLAI/Guarda"),
    "no_sei_processo_fiscalizacao": EncodedString(422, "Nº SEI Processo Fiscalização"),
    "no_sei_relatorio_monitoramento": SimpleField(
        544, "Nº SEI Relatório Monitoramento"
    ),
    "nome_da_entidade": {
        "id": 140,
        "name": "Nome da Entidade",
        "mandatory": True,
        "value": "",
    },
    "observacao_tecnica_amostral": {
        "id": 693,
        "name": "Observação (técnica amostral)",
        "value": "",
    },
    "observacoes": {"id": 1973, "name": "Observações", "value": ""},
    "pai_instaurado_pela_anatel": {
        "id": 160,
        "name": "PAI instaurado pela Anatel?",
        "value": "",
    },
    "potencia_medida": {"id": 81, "name": "Potência medida", "value": ""},
    "precisa_reservar_instrumentos": {
        "id": 596,
        "name": "Precisa reservar instrumentos?",
        "mandatory": True,
        "map": {"1": {"mandatory": ["reserva_de_instrumentos"]}, "0": {}},
        "value": "",
    },
    "procedimentos": {
        "id": 71,
        "name": "Procedimentos",
        "multiple": True,
        "mandatory": True,
        "map": {
            "Nenhum": {},
            "Lacração": {
                "mandatory": ["no_do_lacre", "motivo_de_lai", "no_sei_do_aviso_lai"],
                "optional": ["lai_vinculadas", "no_sei_do_plaiguarda", "gerar_plai"],
            },
            "Apreensão": {
                "mandatory": ["motivo_de_lai", "no_sei_do_aviso_lai"],
                "optional": ["lai_vinculadas", "no_sei_do_plaiguarda", "gerar_plai"],
            },
            "Interrupção": {
                "mandatory": ["motivo_de_lai", "no_sei_do_aviso_lai"],
                "optional": ["lai_vinculadas", "no_sei_do_plaiguarda", "gerar_plai"],
            },
            "Não Cadastrado": {},
            "Notificado": {},
            "A Notificar": {},
            "Liberação/Desinterrupção": {},
            "Orientação ao Usuário": {},
            "Comunicado": {},
            "Deslacrado": {},
            "Vistoriado": {},
            "Emissão Termo Violação de Lacre": {},
            "Apoio a busca e apreensão": {},
            "Investigação/Pesquisa": {},
            "Não Lacrado - Impedimento": {},
            "Não Lacrado - Amparo Judicial": {},
            "Não Lacrado - Responsável Ausente": {},
            "Não Lacrado - Local Fechado": {},
            "Constatação Violação Lacre/Relacrado": {},
            "Constatação Violação Lacre/Impedimento": {},
            "Notícia Crime": {},
            "Monitorado alterado": {},
            "Constatação Encerramento - Informe": {},
            "Levantamento de Dados": {},
            "Análise/coleta de Dados": {},
            "Monitorado": {},
            "Não Lacrado - Desativado": {},
            "Devolução de Produto(s)": {},
        },
        "value": [],
    },
    "qnt_produt_lacradosapreend": {
        "id": 143,
        "name": "Qnt. produt. lacrados/apreend.",
        "value": "",
    },
    "qtd_de_emissoes": {"id": 69, "name": "Qtd. de Emissões", "value": ""},
    "qtd_identificadas": {"id": 731, "name": "Qtd. Identificadas", "value": ""},
    "qtd_licenciadas": {"id": 730, "name": "Qtd. Licenciadas", "value": ""},
    "reserva_de_instrumentos": {
        "id": 597,
        "multiple": True,
        "name": "Reserva de instrumentos",
        "mandatory": True,
        "value": [{"id": "", "valor": "", "texto": ""}],
    },
    "sanada_ou_mitigada": FieldWithOptions(
        159, "Sanada ou mitigada?", True, options=["1", "0"]
    ),
    "servicos_da_inspecao": {
        "id": 57,
        "name": "Serviços da Inspeção",
        "multiple": True,
        "options": SERVICOS,
        "value": [{"valor": "", "texto": ""}],
    },
    "situacao_constatada": {
        "id": 62,
        "name": "Situação constatada",
        "mandatory": True,
        "options": ["Regular", "Irregular", "Inconclusivo", "Não analisado"],
        "value": "",
    },
    "situacao_de_risco_a_vida": {
        "id": 150,
        "name": "Situação de risco à vida?",
        "options": ["Sim", "Não"],
        "value": {"valor": "", "texto": ""},
    },
    # "subtema": {
    # "id": 15,
    # "name": "Subtema",
    # "multiple": True,
    # "value": [{"valor": "", "texto": ""}],
    # },
    # "tema": {
    #     "id": 14,
    #     "name": "Tema",
    #     "multiple": True,
    #     "value": [{"valor": "", "texto": ""}],
    # },
    "tipificacao_da_infracao": {
        "id": 148,
        "name": "Tipificação da infração",
        "value": "",
    },
    "tipo_de_inspecao": {
        "id": 2,
        "name": "Tipo de inspeção",
        "mandatory": True,
        "map": {
            "Bloqueio Administrativo": {
                "mandatory": [
                    "nome_da_entidade",
                    "observacao_tecnica_amostral",
                    "utilizou_algum_instrumento",
                    "utilizou_tecnicas_amostrais",
                ],
                "optional": [],
            },
            "Certificação": {
                "mandatory": [
                    "endereco_da_inspecao",
                    "entidade_com_cadastro_stel",
                    "houve_obice",
                    "latitude_coordenadas",
                    "longitude_coordenadas",
                    "nome_da_entidade",
                    "observacao_tecnica_amostral",
                    "qnt_produt_lacradosapreend",
                    "situacao_constatada",
                    "utilizou_tecnicas_amostrais",
                ],
                "optional": [
                    "area_do_pacp",
                    "cnpjcpf_da_entidade",
                    "documento_instaurador_do_pado",
                    "irregularidade",
                ],
            },
            "Medição de CEMRF (RNI)": {
                "mandatory": [
                    "campo_eletrico__pico_vm",
                    "campo_eletrico_rms_vm",
                    "coordenadas_estacao",
                    "coordenadas_geograficas",
                    "entidade_outorgada",
                    "frequencia_final",
                    "frequencia_inicial",
                    "latitude_coordenadas",
                    "latitude_da_estacao",
                    "longitude_coordenadas",
                    "longitude_da_estacao",
                    "nome_da_entidade" "observacao_tecnica_amostral",
                    "tipo_de_medicao",
                    "servicos_da_inspecao",
                    "unidade_da_frequencia_final",
                    "unidade_da_frequencia_inicial",
                    "utilizou_tecnicas_amostrais",
                ],
                "optional": ["cnpjcpf_da_entidade"],
            },
            "Outorga - Aspectos não Técnicos": {
                "mandatory": [
                    "irregularidade",
                    "observacao_tecnica_amostral",
                    "pai_instaurado_pela_anatel",
                    "servicos_da_inspecao",
                    "situacao_constatada",
                    "utilizou_tecnicas_amostrais",
                ],
                "optional": ["cnpjcpf_da_entidade"],
            },
            "Outorga - Aspectos Técnicos": {
                "mandatory": [
                    # "coordenadas_geograficas",
                    "entidade_outorgada",
                    "esta_em_operacao",
                    "houve_interferencia",
                    "houve_obice",
                    "latitude_coordenadas",
                    "longitude_coordenadas",
                    "observacao_tecnica_amostral",
                    "servicos_da_inspecao",
                    "situacao_constatada",
                    "situacao_de_risco_a_vida",
                    "uso_de_produto_homologado",
                    "utilizou_apoio_policial",
                    "utilizou_tecnicas_amostrais",
                ],
                "optional": [
                    "altura_do_sistema_irradiante",
                    "cnpjcpf_da_entidade",
                    "documento_instaurador_do_pado",
                    "frequencias",
                    "irregularidade",
                    "potencia_medida",
                    "unidade_de_frequencia",
                    "unidade_de_potencia",
                ],
            },
            "Uso do Espectro - Interferência": {
                "mandatory": [
                    "utilizou_tecnicas_amostrais",
                    "observacao_tecnica_amostral",
                    "foi_constatada_interferencia",
                    "observacoes",
                ],
                "optional": [],
            },
            "Uso do Espectro - Monitoração": {
                "mandatory": [
                    "qtd_de_emissoes",
                    "qtd_licenciadas",
                    "qtd_identificadas",
                    "latitude_coordenadas",
                    "longitude_coordenadas",
                    "acao_de_risco_a_vida_criada",
                    "frequencia_inicial",
                    "unidade_da_frequencia_inicial",
                    "frequencia_final",
                    "unidade_da_frequencia_final",
                    "no_sei_relatorio_monitoramento",
                    "coordenadas_geograficas",
                ],
                "optional": [],
            },
            "Uso do Espectro - Não Outorgado": {
                "mandatory": [
                    "entidade_com_cadastro_stel",
                    "uso_de_produto_homologado",
                    "situacao_constatada",
                    "irregularidade",
                    "potencia_medida",
                    "unidade_de_potencia",
                    "frequencias",
                    "unidade_de_frequencia",
                    "utilizou_apoio_policial",
                    "qnt_produt_lacradosapreend",
                    "tipificacao_da_infracao",
                    "houve_interferencia",
                    "situacao_de_risco_a_vida",
                    "latitude_coordenadas",
                    "longitude_coordenadas",
                    "identificacao_da_nao_outorgada",
                    "utilizou_tecnicas_amostrais",
                    "observacao_tecnica_amostral",
                    "coordenadas_geograficas",
                ],
                "optional": [],
            },
        },
        "value": {"valor": "", "texto": ""},
    },
    "tipo_de_medicao": {"id": 193, "name": "Tipo de medição", "value": ""},
    "tipo_do_processo_plai": {
        "id": 426,
        "name": "Tipo do Processo PLAI",
        "options": [
            "Gestão da Fiscalização: Lacração, Apreensão e Interrupção",
            "Gestão da Fiscalização: Processo de Guarda",
        ],
        "value": "",
    },
    "total_de_horas": {"id": 1789, "name": "Total de horas", "value": ""},
    "ufmunicipio": {
        "id": 31,
        "name": "UF/Município",
        "mandatory": True,
        "multiple": True,
        "options": MUNICIPIOS,
        "value": [{"valor": "", "texto": ""}],
    },
    "unidade_da_frequencia_final": {
        "id": 159,
        "name": "Unidade da frequência final",
        "mandatory": True,
        "options": [
            "Hz",
            "kHz",
            "MHz",
            "GHz",
            "THz",
        ],
        "value": "",
    },
    "unidade_da_frequencia_inicial": {
        "id": 157,
        "name": "Unidade da frequência inicial",
        "mandatory": True,
        "options": [
            "Hz",
            "kHz",
            "MHz",
            "GHz",
            "THz",
        ],
        "value": "",
    },
    "unidade_de_frequencia": {"id": 84, "name": "Unidade de Frequência", "value": ""},
    "unidade_de_potencia": {"id": 82, "name": "Unidade de Potência", "value": ""},
    "uso_de_produto_homologado": {
        "id": 132,
        "name": "Uso de produto homologado?",
        "map": {"1": {"optional": ["no_de_homologacao"]}, "0": {}},
        "value": "",
    },
    "utilizou_algum_instrumento": {
        "id": 598,
        "name": "Utilizou algum instrumento?",
        "mandatory": True,
        "map": {
            "1": {
                "mandatory": ["instrumentos_utilizados"],
                "optional": ["copiar_instrumento_da_reserva"],
            },
            "0": {},
        },
        "value": "",
    },
    "utilizou_apoio_policial": {
        "id": 75,
        "name": "Utilizou apoio policial?",
        "options": [
            "Nenhum",
            "Polícia Civil",
            "Polícia Militar",
            "Polícia Federal",
            "Polícia Rodoviária Federal",
        ],
        "value": "",
    },
    "utilizou_tecnicas_amostrais": {
        "id": 692,
        "name": "Utilizou técnicas amostrais?",
        "mandatory": True,
        "options": ["Usou técnicas amostrais", "Não usou técnicas amostrais"],
        "value": "",
    },
}
