name: fiscaliza
channels:
  - conda-forge
  - defaults
dependencies:
  - backports=1.0
  - backports.tarfile=1.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cmarkgfm=0.8.0
  - colorama=0.4.6
  - docutils=0.21.2
  - fastcore=1.5.46
  - idna=3.7
  - importlib-metadata=7.2.0
  - importlib_metadata=7.2.0
  - importlib_resources=6.4.0
  - jaraco.classes=3.4.0
  - jaraco.context=5.3.0
  - jaraco.functools=4.0.0
  - keyring=25.2.1
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - mdurl=0.1.2
  - more-itertools=10.3.0
  - nh3=0.2.17
  - openssl=3.3.1
  - packaging=24.1
  - pip=24.0
  - pkginfo=1.11.1
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dotenv=1.0.1
  - python-redmine=2.4.0
  - python_abi=3.11
  - pywin32-ctypes=0.2.2
  - readme_renderer=42.0
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rfc3986=2.0.0
  - rich=13.7.1
  - ruff=0.4.9
  - setuptools=70.1.0
  - shellingham=1.5.4
  - tabulate=0.9.0
  - tk=8.6.13
  - twine=5.1.0
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unidecode=1.3.8
  - urllib3=2.2.2
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - zipp=3.19.2
